### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by jose1711** [ahockersten/liero#16]
It would be nice if `README.md` mentions the instructions how to convert TC. Something like this: https://www.reddit.com/r/linux/comments/3u9hna/how_to_get_liero_v136_running_on_linux/

**Comment by ahockersten** [comment]
I don't really have any interest in running Liero TCs, and the repo already includes the files necessary to run the default Liero ruleset. If you want to write instructions and verify that they work, I'd be willing to accept a patch with instructions for how to use the tctool, though. :)

**Comment by jose1711** [comment]
Can you please detail how to run 'vanilla' openliero? When trying to execute the binary I got this:
```
./openliero      
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not read ./TC/Liero v1.33/tc.cfg
```

**Comment by ahockersten** [comment]
If you download any of the provided binaries, they are packaged correctly. For running your own builds from within the source tree, it's been so long since I tried that I don't recall how to do that. You probably need to copy the pkg/TC folder to be in the same folder as where you are trying to run the openliero binary from.

**Comment by ahockersten** [comment]
Specifically, see the last step of "Building on Linux and Mac", which says 'Copy everything from the pkg directory to the root directory used for the build'.

Did you do this?

**Comment by jose1711** [comment]
Sorry, you're absolutely right. It's all there. Closing.
